### ISSUE TITLE
-o xml exports as .db

### ISSUE THREAD

**Issue by obesechess** [tmo1/sms-db#1]
Hi there,

It's entirely possible I just don't understand the functionality of this tool. My understanding is that this will export the signal-backup.db file (or other database files) as xml, based on:

> Currently, the only supported output format is Synctech's XML format.

However, after running the tool, even if I set my output to xml, I just end up with a new signal-backup.db, albeit one that is much closer in size to my initial Signal .backup file. What am I doing wrong?

Thanks!

EDIT 2: I should add that this is all way over my head, technologically. I'm pretty sharp, but not a "computer guy." I am literally just trying to get my Signal backups readable as there is like seven years of stuff on there that I couldn't keep after switching from Android to iPhone. So opening up an SQL Database of thousands of hashes is a bit daunting.

**Comment by tmo1** [comment]
You're on the right track, but you don't want `-o xml` - you want `-f xml -o filename`

In other words, to export the Signal database to XML, issue the following two commands. First:

` sms-db.pl -f signal -i signal path/to/decoded-signal/backup/directory`

This will import your Signal messages into a new database (named `sms-db.db` by default) in sms-db's internal format. Then:

` sms-db.pl -f xml -o filename`

This will export the messages from the new database in XML format to a file named `filename`

If it still doesn't work, please post the output of both commands.

**Comment by obesechess** [comment]
Ah, got it. It was the second step that I missed. I will give that a shot. I believe that after decoding my 6.88GB .backup file, it was called `signal-backup.db` and was only a few mb. After running (if memory serves, it was kind of a whirlwind) 
`sms-db.pl -f signal -i path/to/directory/signal-backup.db` 
I got a second signal-backup.db that was 6.88GB.

So I just take that second signal-backup.db, or whatever the name of the output .db file is, and then run
`sms-db.pl -f xml -o filename` - is this right? How do I know which .db file to point the script at, for lack of a better word? Do I put that same file as the -i, or what?

Thank you!

**Comment by tmo1** [comment]
> Ah, got it. It was the second step that I missed. I will give that a shot. I believe that after decoding my 6.88GB .backup file, it was called signal-backup.db and was only a few mb.

That's the database with the metadata (sender, recipient, etc.) as well the body of SMS messages and the text parts of MMS messages. The attachments (non-text parts, e.g., images and videos) of MMS messages, are stored as individual files in the `attachment` subdirectory under the main backup directory. `signal-backup.db` is small because most of the data is in large attachments, which are stored outside the database.

> After running (if memory serves, it was kind of a whirlwind) `sms-db.pl -f signal -i path/to/directory/signal-backup.db` I got a second signal-backup.db that was 6.88GB.

You don't point sms-db directly at the `signal-backup.db` file - you point it at the root directory of the backup (the directory containing `signal-backup.db`). It should be named something like `signal-2020-12-02-nn-nn-nn`, so:

`sms-db.pl -i signal-2020-12-02-nn-nn-nn -f signal`

> So I just take that second signal-backup.db, or whatever the name of the output .db file is, and then run `sms-db.pl -f xml -o filename` - is this right? How do I know which .db file to point the script at, for lack of a better word? Do I put that same file as the -i, or what?

For the second command, you point sms-db at the database file created by the first step. By default, this is `sms-db.db` (for both the import and export steps), unless you've set it to something else with the `-d` flag. So just:

`sms-db.pl -o filename -f xml`

> Thank you!

Let me know how it goes!

**Comment by obesechess** [comment]
That's right! I pointed it at the directory because it found the "attachments" folder as well. So, as before, I navigate to that folder in my perl shell (or whatever it's called, in this case I'm using Strawberry) and then
`perl sms-db.pl -o desired-filename -f xml`
just like that?
Or do I need to run both steps in succession again? Or do I do something else?

This is the most I've done with code since putting HTML on my MySpace in 2006 so I appreciate your patience.

**Comment by tmo1** [comment]
> That's right! I pointed it at the directory because it found the "attachments" folder as well. So, as before, I navigate to that folder in my perl shell (or whatever it's called, in this case I'm using Strawberry) and then `perl sms-db.pl -o desired-filename -f xml`

That's the right format for the second command.

> just like that? Or do I need to run both steps in succession again? Or do I do something else?

I'd do the first step first, just to make sure. Just run both commands from whatever shell you're using, the first first and the second second. If both commands work correctly, the output of the first should look like this:

```
~$ sms-db.pl -i /path/to/signal-2020-12-02-nn-nn-nn/ -f signal
sms-db version 0.3
Importing messages from '/path/to/signal-2020-12-02-nn-nn-nn/' ...
Total messages seen:		nnnn
Total messages imported:	nnnn
Duplicate messages:		0
Ignored messages:		0
Total message parts imported:	mmmm
Messages in database:		nnnn
Elapsed time:			xxx.xxxxxx seconds
```

And the output of the second like this:

```
~$ sms-db.pl -f xml -o filename
sms-db version 0.3
Exporting messages to 'filename' ...
Total messages exported:	nnnn
Elapsed time:			yyy.yyyyyy seconds
 ```

Note that with a large database, the commands could take a few minutes to finish, depending on your hardware, so have patience and wait until you end up back at the prompt.

> This is the most I've done with code since putting HTML on my MySpace in 2006 so I appreciate your patience.

Good luck!

**Comment by obesechess** [comment]
Forgot to let you know, I think this worked - it's been "exporting messages to 'outputtest'" for like 45 minutes, but it's also a 7GB file, so. I'll keep you posted if it doesn't work but so far so good. Thank you again!

**Comment by obesechess** [comment]
Alright, it exported but not as an .xml, windows is just reading it as a "file." My full input/output is:

```
J:\> perl J:\sms-db-main\sms-db.pl -f xml -o outputtest
sms-db version 0.3
Exporting messages to 'outputtest' ...
Total messages exported:        78444
Elapsed time:                   2365.769273 seconds
```

and the resulting file was just "outputtest," no file extension. Changing the file extension manually to .xml did not work, the .xml still doesn't open in any browser nor in any of the scripts/apps designed to read xml files from SMS Backup/Restore. Is this because the file is so dang big (now 10GB)? Thoughts?

Thanks again!

**Comment by tmo1** [comment]
Okay, so sms-db thinks that it's working ;) The reason the output file did not have an extension is because you did not specify one. To do so, use `-o outputtest.xml`.

I really don't know why it doesn't open. The size certainly could be an issue. Why don't you try doing an export of just SMS messages - run just the last command again, but with `-t sms` added, so:
`J:\> perl J:\sms-db-main\sms-db.pl -f xml -o outputtest.xml -t sms`
Again, just that command - not the earlier import command. See if you can access the resulting file. If you still can't, try opening the file in Notepad or whatever text editor you use and see what it looks like.

**Comment by obesechess** [comment]
I will try to redo it as `-o outputtest.xml` rather than `-o outputtest` and if that doesn't work I'll give it a shot with running it as just the sms. Thanks again for all your help!

**Comment by obesechess** [comment]
Well, I'm sure I did it right, but it's just too damn big (9.45GB again) - I'll try with just the SMS. Thank you!

**Comment by obesechess** [comment]
Ha! It worked. SyncTech has an online viewer you can upload the XML to at http://synctech.com.au/view-backup, that was the missing link. Thanks again for all the help, this is a great script and obviously the support is top notch. :)

**Comment by tmo1** [comment]
:) You're very welcome - I'm glad we got it working.
